-- Quartz 2.5.2 official MySQL/InnoDB schema, managed by Flyway instead of
-- spring.quartz.jdbc.initialize-schema so production startup stays fail-closed.
CREATE TABLE QRTZ_JOB_DETAILS (
    SCHED_NAME varchar(120) NOT NULL,
    JOB_NAME varchar(190) NOT NULL,
    JOB_GROUP varchar(190) NOT NULL,
    DESCRIPTION varchar(250) NULL,
    JOB_CLASS_NAME varchar(250) NOT NULL,
    IS_DURABLE varchar(1) NOT NULL,
    IS_NONCONCURRENT varchar(1) NOT NULL,
    IS_UPDATE_DATA varchar(1) NOT NULL,
    REQUESTS_RECOVERY varchar(1) NOT NULL,
    JOB_DATA blob NULL,
    PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
) ENGINE=InnoDB;

CREATE TABLE QRTZ_TRIGGERS (
    SCHED_NAME varchar(120) NOT NULL,
    TRIGGER_NAME varchar(190) NOT NULL,
    TRIGGER_GROUP varchar(190) NOT NULL,
    JOB_NAME varchar(190) NOT NULL,
    JOB_GROUP varchar(190) NOT NULL,
    DESCRIPTION varchar(250) NULL,
    NEXT_FIRE_TIME bigint NULL,
    PREV_FIRE_TIME bigint NULL,
    PRIORITY integer NULL,
    TRIGGER_STATE varchar(16) NOT NULL,
    TRIGGER_TYPE varchar(8) NOT NULL,
    START_TIME bigint NOT NULL,
    END_TIME bigint NULL,
    CALENDAR_NAME varchar(190) NULL,
    MISFIRE_INSTR smallint NULL,
    JOB_DATA blob NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT FK_QRTZ_TRIGGERS_JOB_DETAILS
        FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
        REFERENCES QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP)
) ENGINE=InnoDB;

CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
    SCHED_NAME varchar(120) NOT NULL,
    TRIGGER_NAME varchar(190) NOT NULL,
    TRIGGER_GROUP varchar(190) NOT NULL,
    REPEAT_COUNT bigint NOT NULL,
    REPEAT_INTERVAL bigint NOT NULL,
    TIMES_TRIGGERED bigint NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT FK_QRTZ_SIMPLE_TRIGGERS_TRIGGERS
        FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB;

CREATE TABLE QRTZ_CRON_TRIGGERS (
    SCHED_NAME varchar(120) NOT NULL,
    TRIGGER_NAME varchar(190) NOT NULL,
    TRIGGER_GROUP varchar(190) NOT NULL,
    CRON_EXPRESSION varchar(120) NOT NULL,
    TIME_ZONE_ID varchar(80) NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT FK_QRTZ_CRON_TRIGGERS_TRIGGERS
        FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB;

CREATE TABLE QRTZ_SIMPROP_TRIGGERS (
    SCHED_NAME varchar(120) NOT NULL,
    TRIGGER_NAME varchar(190) NOT NULL,
    TRIGGER_GROUP varchar(190) NOT NULL,
    STR_PROP_1 varchar(512) NULL,
    STR_PROP_2 varchar(512) NULL,
    STR_PROP_3 varchar(512) NULL,
    INT_PROP_1 integer NULL,
    INT_PROP_2 integer NULL,
    LONG_PROP_1 bigint NULL,
    LONG_PROP_2 bigint NULL,
    DEC_PROP_1 numeric(13, 4) NULL,
    DEC_PROP_2 numeric(13, 4) NULL,
    BOOL_PROP_1 varchar(1) NULL,
    BOOL_PROP_2 varchar(1) NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT FK_QRTZ_SIMPROP_TRIGGERS_TRIGGERS
        FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB;

CREATE TABLE QRTZ_BLOB_TRIGGERS (
    SCHED_NAME varchar(120) NOT NULL,
    TRIGGER_NAME varchar(190) NOT NULL,
    TRIGGER_GROUP varchar(190) NOT NULL,
    BLOB_DATA blob NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    CONSTRAINT FK_QRTZ_BLOB_TRIGGERS_TRIGGERS
        FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB;

CREATE TABLE QRTZ_CALENDARS (
    SCHED_NAME varchar(120) NOT NULL,
    CALENDAR_NAME varchar(190) NOT NULL,
    CALENDAR blob NOT NULL,
    PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
) ENGINE=InnoDB;

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (
    SCHED_NAME varchar(120) NOT NULL,
    TRIGGER_GROUP varchar(190) NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB;

CREATE TABLE QRTZ_FIRED_TRIGGERS (
    SCHED_NAME varchar(120) NOT NULL,
    ENTRY_ID varchar(95) NOT NULL,
    TRIGGER_NAME varchar(190) NOT NULL,
    TRIGGER_GROUP varchar(190) NOT NULL,
    INSTANCE_NAME varchar(190) NOT NULL,
    FIRED_TIME bigint NOT NULL,
    SCHED_TIME bigint NOT NULL,
    PRIORITY integer NOT NULL,
    STATE varchar(16) NOT NULL,
    JOB_NAME varchar(190) NULL,
    JOB_GROUP varchar(190) NULL,
    IS_NONCONCURRENT varchar(1) NULL,
    REQUESTS_RECOVERY varchar(1) NULL,
    PRIMARY KEY (SCHED_NAME, ENTRY_ID)
) ENGINE=InnoDB;

CREATE TABLE QRTZ_SCHEDULER_STATE (
    SCHED_NAME varchar(120) NOT NULL,
    INSTANCE_NAME varchar(190) NOT NULL,
    LAST_CHECKIN_TIME bigint NOT NULL,
    CHECKIN_INTERVAL bigint NOT NULL,
    PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
) ENGINE=InnoDB;

CREATE TABLE QRTZ_LOCKS (
    SCHED_NAME varchar(120) NOT NULL,
    LOCK_NAME varchar(40) NOT NULL,
    PRIMARY KEY (SCHED_NAME, LOCK_NAME)
) ENGINE=InnoDB;

CREATE INDEX IDX_QRTZ_J_REQ_RECOVERY ON QRTZ_JOB_DETAILS (SCHED_NAME, REQUESTS_RECOVERY);
CREATE INDEX IDX_QRTZ_J_GRP ON QRTZ_JOB_DETAILS (SCHED_NAME, JOB_GROUP);

CREATE INDEX IDX_QRTZ_T_J ON QRTZ_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP);
CREATE INDEX IDX_QRTZ_T_JG ON QRTZ_TRIGGERS (SCHED_NAME, JOB_GROUP);
CREATE INDEX IDX_QRTZ_T_C ON QRTZ_TRIGGERS (SCHED_NAME, CALENDAR_NAME);
CREATE INDEX IDX_QRTZ_T_G ON QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_GROUP);
CREATE INDEX IDX_QRTZ_T_STATE ON QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_N_STATE ON QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_N_G_STATE ON QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME ON QRTZ_TRIGGERS (SCHED_NAME, NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_ST ON QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_MISFIRE ON QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE
    ON QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE_GRP
    ON QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE);

CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME ON QRTZ_FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME);
CREATE INDEX IDX_QRTZ_FT_INST_JOB_REQ_RCVRY
    ON QRTZ_FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY);
CREATE INDEX IDX_QRTZ_FT_J_G ON QRTZ_FIRED_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP);
CREATE INDEX IDX_QRTZ_FT_JG ON QRTZ_FIRED_TRIGGERS (SCHED_NAME, JOB_GROUP);
CREATE INDEX IDX_QRTZ_FT_T_G ON QRTZ_FIRED_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);
CREATE INDEX IDX_QRTZ_FT_TG ON QRTZ_FIRED_TRIGGERS (SCHED_NAME, TRIGGER_GROUP);
